export type Country = { code: string; name: string; nameAr: string; flag: string };

export const COUNTRIES: Country[] = [
  { code: "AC", name: "Ascension Island", nameAr: "جزيرة أسينشيون", flag: "🇦🇨" },
  { code: "AD", name: "Andorra", nameAr: "أندورا", flag: "🇦🇩" },
  { code: "AE", name: "United Arab Emirates", nameAr: "الإمارات العربية المتحدة", flag: "🇦🇪" },
  { code: "AF", name: "Afghanistan", nameAr: "أفغانستان", flag: "🇦🇫" },
  { code: "AG", name: "Antigua & Barbuda", nameAr: "أنتيغوا وبربودا", flag: "🇦🇬" },
  { code: "AI", name: "Anguilla", nameAr: "أنغويلا", flag: "🇦🇮" },
  { code: "AL", name: "Albania", nameAr: "ألبانيا", flag: "🇦🇱" },
  { code: "AM", name: "Armenia", nameAr: "أرمينيا", flag: "🇦🇲" },
  { code: "AN", name: "Curaçao", nameAr: "كوراساو", flag: "🇦🇳" },
  { code: "AO", name: "Angola", nameAr: "أنغولا", flag: "🇦🇴" },
  { code: "AQ", name: "Antarctica", nameAr: "أنتاركتيكا", flag: "🇦🇶" },
  { code: "AR", name: "Argentina", nameAr: "الأرجنتين", flag: "🇦🇷" },
  { code: "AS", name: "American Samoa", nameAr: "ساموا الأمريكية", flag: "🇦🇸" },
  { code: "AT", name: "Austria", nameAr: "النمسا", flag: "🇦🇹" },
  { code: "AU", name: "Australia", nameAr: "أستراليا", flag: "🇦🇺" },
  { code: "AW", name: "Aruba", nameAr: "أروبا", flag: "🇦🇼" },
  { code: "AX", name: "Åland Islands", nameAr: "جزر آلاند", flag: "🇦🇽" },
  { code: "AZ", name: "Azerbaijan", nameAr: "أذربيجان", flag: "🇦🇿" },
  { code: "BA", name: "Bosnia & Herzegovina", nameAr: "البوسنة والهرسك", flag: "🇧🇦" },
  { code: "BB", name: "Barbados", nameAr: "بربادوس", flag: "🇧🇧" },
  { code: "BD", name: "Bangladesh", nameAr: "بنغلاديش", flag: "🇧🇩" },
  { code: "BE", name: "Belgium", nameAr: "بلجيكا", flag: "🇧🇪" },
  { code: "BF", name: "Burkina Faso", nameAr: "بوركينا فاسو", flag: "🇧🇫" },
  { code: "BG", name: "Bulgaria", nameAr: "بلغاريا", flag: "🇧🇬" },
  { code: "BH", name: "Bahrain", nameAr: "البحرين", flag: "🇧🇭" },
  { code: "BI", name: "Burundi", nameAr: "بوروندي", flag: "🇧🇮" },
  { code: "BJ", name: "Benin", nameAr: "بنين", flag: "🇧🇯" },
  { code: "BL", name: "St. Barthélemy", nameAr: "سان بارتليمي", flag: "🇧🇱" },
  { code: "BM", name: "Bermuda", nameAr: "برمودا", flag: "🇧🇲" },
  { code: "BN", name: "Brunei", nameAr: "بروناي", flag: "🇧🇳" },
  { code: "BO", name: "Bolivia", nameAr: "بوليفيا", flag: "🇧🇴" },
  { code: "BQ", name: "Caribbean Netherlands", nameAr: "هولندا الكاريبية", flag: "🇧🇶" },
  { code: "BR", name: "Brazil", nameAr: "البرازيل", flag: "🇧🇷" },
  { code: "BS", name: "Bahamas", nameAr: "جزر البهاما", flag: "🇧🇸" },
  { code: "BT", name: "Bhutan", nameAr: "بوتان", flag: "🇧🇹" },
  { code: "BU", name: "Myanmar (Burma)", nameAr: "ميانمار (بورما)", flag: "🇧🇺" },
  { code: "BV", name: "Bouvet Island", nameAr: "جزيرة بوفيه", flag: "🇧🇻" },
  { code: "BW", name: "Botswana", nameAr: "بوتسوانا", flag: "🇧🇼" },
  { code: "BY", name: "Belarus", nameAr: "بيلاروس", flag: "🇧🇾" },
  { code: "BZ", name: "Belize", nameAr: "بليز", flag: "🇧🇿" },
  { code: "CA", name: "Canada", nameAr: "كندا", flag: "🇨🇦" },
  { code: "CC", name: "Cocos (Keeling) Islands", nameAr: "جزر كوكوس (كيلينغ)", flag: "🇨🇨" },
  { code: "CD", name: "Congo - Kinshasa", nameAr: "الكونغو - كينشاسا", flag: "🇨🇩" },
  { code: "CF", name: "Central African Republic", nameAr: "جمهورية أفريقيا الوسطى", flag: "🇨🇫" },
  { code: "CG", name: "Congo - Brazzaville", nameAr: "الكونغو - برازافيل", flag: "🇨🇬" },
  { code: "CH", name: "Switzerland", nameAr: "سويسرا", flag: "🇨🇭" },
  { code: "CI", name: "Côte d’Ivoire", nameAr: "ساحل العاج", flag: "🇨🇮" },
  { code: "CK", name: "Cook Islands", nameAr: "جزر كوك", flag: "🇨🇰" },
  { code: "CL", name: "Chile", nameAr: "تشيلي", flag: "🇨🇱" },
  { code: "CM", name: "Cameroon", nameAr: "الكاميرون", flag: "🇨🇲" },
  { code: "CN", name: "China", nameAr: "الصين", flag: "🇨🇳" },
  { code: "CO", name: "Colombia", nameAr: "كولومبيا", flag: "🇨🇴" },
  { code: "CP", name: "Clipperton Island", nameAr: "جزيرة كليبيرتون", flag: "🇨🇵" },
  { code: "CQ", name: "Sark", nameAr: "CQ", flag: "🇨🇶" },
  { code: "CR", name: "Costa Rica", nameAr: "كوستاريكا", flag: "🇨🇷" },
  { code: "CS", name: "Serbia", nameAr: "صربيا", flag: "🇨🇸" },
  { code: "CU", name: "Cuba", nameAr: "كوبا", flag: "🇨🇺" },
  { code: "CV", name: "Cape Verde", nameAr: "الرأس الأخضر", flag: "🇨🇻" },
  { code: "CW", name: "Curaçao", nameAr: "كوراساو", flag: "🇨🇼" },
  { code: "CX", name: "Christmas Island", nameAr: "جزيرة كريسماس", flag: "🇨🇽" },
  { code: "CY", name: "Cyprus", nameAr: "قبرص", flag: "🇨🇾" },
  { code: "CZ", name: "Czechia", nameAr: "التشيك", flag: "🇨🇿" },
  { code: "DD", name: "Germany", nameAr: "ألمانيا", flag: "🇩🇩" },
  { code: "DE", name: "Germany", nameAr: "ألمانيا", flag: "🇩🇪" },
  { code: "DG", name: "Diego Garcia", nameAr: "دييغو غارسيا", flag: "🇩🇬" },
  { code: "DJ", name: "Djibouti", nameAr: "جيبوتي", flag: "🇩🇯" },
  { code: "DK", name: "Denmark", nameAr: "الدانمرك", flag: "🇩🇰" },
  { code: "DM", name: "Dominica", nameAr: "دومينيكا", flag: "🇩🇲" },
  { code: "DO", name: "Dominican Republic", nameAr: "جمهورية الدومينيكان", flag: "🇩🇴" },
  { code: "DY", name: "Benin", nameAr: "بنين", flag: "🇩🇾" },
  { code: "DZ", name: "Algeria", nameAr: "الجزائر", flag: "🇩🇿" },
  { code: "EA", name: "Ceuta & Melilla", nameAr: "سيوتا وميليلا", flag: "🇪🇦" },
  { code: "EC", name: "Ecuador", nameAr: "الإكوادور", flag: "🇪🇨" },
  { code: "EE", name: "Estonia", nameAr: "إستونيا", flag: "🇪🇪" },
  { code: "EG", name: "Egypt", nameAr: "مصر", flag: "🇪🇬" },
  { code: "EH", name: "Western Sahara", nameAr: "الصحراء الغربية", flag: "🇪🇭" },
  { code: "ER", name: "Eritrea", nameAr: "إريتريا", flag: "🇪🇷" },
  { code: "ES", name: "Spain", nameAr: "إسبانيا", flag: "🇪🇸" },
  { code: "ET", name: "Ethiopia", nameAr: "إثيوبيا", flag: "🇪🇹" },
  { code: "EU", name: "European Union", nameAr: "الاتحاد الأوروبي", flag: "🇪🇺" },
  { code: "EZ", name: "Eurozone", nameAr: "منطقة اليورو", flag: "🇪🇿" },
  { code: "FI", name: "Finland", nameAr: "فنلندا", flag: "🇫🇮" },
  { code: "FJ", name: "Fiji", nameAr: "فيجي", flag: "🇫🇯" },
  { code: "FK", name: "Falkland Islands", nameAr: "جزر فوكلاند", flag: "🇫🇰" },
  { code: "FM", name: "Micronesia", nameAr: "ميكرونيزيا", flag: "🇫🇲" },
  { code: "FO", name: "Faroe Islands", nameAr: "جزر فارو", flag: "🇫🇴" },
  { code: "FR", name: "France", nameAr: "فرنسا", flag: "🇫🇷" },
  { code: "FX", name: "France", nameAr: "فرنسا", flag: "🇫🇽" },
  { code: "GA", name: "Gabon", nameAr: "الغابون", flag: "🇬🇦" },
  { code: "GB", name: "United Kingdom", nameAr: "المملكة المتحدة", flag: "🇬🇧" },
  { code: "GB-ENG", name: "England", nameAr: "إنجلترا", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { code: "GB-SCT", name: "Scotland", nameAr: "إسكتلندا", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { code: "GB-WLS", name: "Wales", nameAr: "ويلز", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  { code: "GB-NIR", name: "Northern Ireland", nameAr: "أيرلندا الشمالية", flag: "🇬🇧" },
  { code: "GD", name: "Grenada", nameAr: "غرينادا", flag: "🇬🇩" },
  { code: "GE", name: "Georgia", nameAr: "جورجيا", flag: "🇬🇪" },
  { code: "GF", name: "French Guiana", nameAr: "غويانا الفرنسية", flag: "🇬🇫" },
  { code: "GG", name: "Guernsey", nameAr: "غيرنزي", flag: "🇬🇬" },
  { code: "GH", name: "Ghana", nameAr: "غانا", flag: "🇬🇭" },
  { code: "GI", name: "Gibraltar", nameAr: "جبل طارق", flag: "🇬🇮" },
  { code: "GL", name: "Greenland", nameAr: "غرينلاند", flag: "🇬🇱" },
  { code: "GM", name: "Gambia", nameAr: "غامبيا", flag: "🇬🇲" },
  { code: "GN", name: "Guinea", nameAr: "غينيا", flag: "🇬🇳" },
  { code: "GP", name: "Guadeloupe", nameAr: "غوادلوب", flag: "🇬🇵" },
  { code: "GQ", name: "Equatorial Guinea", nameAr: "غينيا الاستوائية", flag: "🇬🇶" },
  { code: "GR", name: "Greece", nameAr: "اليونان", flag: "🇬🇷" },
  { code: "GS", name: "South Georgia & South Sandwich Islands", nameAr: "جورجيا الجنوبية وجزر ساندويتش الجنوبية", flag: "🇬🇸" },
  { code: "GT", name: "Guatemala", nameAr: "غواتيمالا", flag: "🇬🇹" },
  { code: "GU", name: "Guam", nameAr: "غوام", flag: "🇬🇺" },
  { code: "GW", name: "Guinea-Bissau", nameAr: "غينيا بيساو", flag: "🇬🇼" },
  { code: "GY", name: "Guyana", nameAr: "غيانا", flag: "🇬🇾" },
  { code: "HK", name: "Hong Kong SAR China", nameAr: "هونغ كونغ الصينية (منطقة إدارية خاصة)", flag: "🇭🇰" },
  { code: "HM", name: "Heard & McDonald Islands", nameAr: "جزيرة هيرد وجزر ماكدونالد", flag: "🇭🇲" },
  { code: "HN", name: "Honduras", nameAr: "هندوراس", flag: "🇭🇳" },
  { code: "HR", name: "Croatia", nameAr: "كرواتيا", flag: "🇭🇷" },
  { code: "HT", name: "Haiti", nameAr: "هايتي", flag: "🇭🇹" },
  { code: "HU", name: "Hungary", nameAr: "هنغاريا", flag: "🇭🇺" },
  { code: "HV", name: "Burkina Faso", nameAr: "بوركينا فاسو", flag: "🇭🇻" },
  { code: "IC", name: "Canary Islands", nameAr: "جزر الكناري", flag: "🇮🇨" },
  { code: "ID", name: "Indonesia", nameAr: "إندونيسيا", flag: "🇮🇩" },
  { code: "IE", name: "Ireland", nameAr: "أيرلندا", flag: "🇮🇪" },
  { code: "IL", name: "Israel", nameAr: "إسرائيل", flag: "🇮🇱" },
  { code: "IM", name: "Isle of Man", nameAr: "جزيرة مان", flag: "🇮🇲" },
  { code: "IN", name: "India", nameAr: "الهند", flag: "🇮🇳" },
  { code: "IO", name: "British Indian Ocean Territory", nameAr: "الإقليم البريطاني في المحيط الهندي", flag: "🇮🇴" },
  { code: "IQ", name: "Iraq", nameAr: "العراق", flag: "🇮🇶" },
  { code: "IR", name: "Iran", nameAr: "إيران", flag: "🇮🇷" },
  { code: "IS", name: "Iceland", nameAr: "آيسلندا", flag: "🇮🇸" },
  { code: "IT", name: "Italy", nameAr: "إيطاليا", flag: "🇮🇹" },
  { code: "JE", name: "Jersey", nameAr: "جيرسي", flag: "🇯🇪" },
  { code: "JM", name: "Jamaica", nameAr: "جامايكا", flag: "🇯🇲" },
  { code: "JO", name: "Jordan", nameAr: "الأردن", flag: "🇯🇴" },
  { code: "JP", name: "Japan", nameAr: "اليابان", flag: "🇯🇵" },
  { code: "KE", name: "Kenya", nameAr: "كينيا", flag: "🇰🇪" },
  { code: "KG", name: "Kyrgyzstan", nameAr: "قيرغيزستان", flag: "🇰🇬" },
  { code: "KH", name: "Cambodia", nameAr: "كمبوديا", flag: "🇰🇭" },
  { code: "KI", name: "Kiribati", nameAr: "كيريباتي", flag: "🇰🇮" },
  { code: "KM", name: "Comoros", nameAr: "جزر القمر", flag: "🇰🇲" },
  { code: "KN", name: "St. Kitts & Nevis", nameAr: "سانت كيتس ونيفيس", flag: "🇰🇳" },
  { code: "KP", name: "North Korea", nameAr: "كوريا الشمالية", flag: "🇰🇵" },
  { code: "KR", name: "South Korea", nameAr: "كوريا الجنوبية", flag: "🇰🇷" },
  { code: "KW", name: "Kuwait", nameAr: "الكويت", flag: "🇰🇼" },
  { code: "KY", name: "Cayman Islands", nameAr: "جزر كايمان", flag: "🇰🇾" },
  { code: "KZ", name: "Kazakhstan", nameAr: "كازاخستان", flag: "🇰🇿" },
  { code: "LA", name: "Laos", nameAr: "لاوس", flag: "🇱🇦" },
  { code: "LB", name: "Lebanon", nameAr: "لبنان", flag: "🇱🇧" },
  { code: "LC", name: "St. Lucia", nameAr: "سانت لوسيا", flag: "🇱🇨" },
  { code: "LI", name: "Liechtenstein", nameAr: "ليختنشتاين", flag: "🇱🇮" },
  { code: "LK", name: "Sri Lanka", nameAr: "سريلانكا", flag: "🇱🇰" },
  { code: "LR", name: "Liberia", nameAr: "ليبيريا", flag: "🇱🇷" },
  { code: "LS", name: "Lesotho", nameAr: "ليسوتو", flag: "🇱🇸" },
  { code: "LT", name: "Lithuania", nameAr: "ليتوانيا", flag: "🇱🇹" },
  { code: "LU", name: "Luxembourg", nameAr: "لوكسمبورغ", flag: "🇱🇺" },
  { code: "LV", name: "Latvia", nameAr: "لاتفيا", flag: "🇱🇻" },
  { code: "LY", name: "Libya", nameAr: "ليبيا", flag: "🇱🇾" },
  { code: "MA", name: "Morocco", nameAr: "المغرب", flag: "🇲🇦" },
  { code: "MC", name: "Monaco", nameAr: "موناكو", flag: "🇲🇨" },
  { code: "MD", name: "Moldova", nameAr: "مولدوفا", flag: "🇲🇩" },
  { code: "ME", name: "Montenegro", nameAr: "الجبل الأسود", flag: "🇲🇪" },
  { code: "MF", name: "St. Martin", nameAr: "سان مارتن", flag: "🇲🇫" },
  { code: "MG", name: "Madagascar", nameAr: "مدغشقر", flag: "🇲🇬" },
  { code: "MH", name: "Marshall Islands", nameAr: "جزر مارشال", flag: "🇲🇭" },
  { code: "MK", name: "North Macedonia", nameAr: "مقدونيا الشمالية", flag: "🇲🇰" },
  { code: "ML", name: "Mali", nameAr: "مالي", flag: "🇲🇱" },
  { code: "MM", name: "Myanmar (Burma)", nameAr: "ميانمار (بورما)", flag: "🇲🇲" },
  { code: "MN", name: "Mongolia", nameAr: "منغوليا", flag: "🇲🇳" },
  { code: "MO", name: "Macao SAR China", nameAr: "منطقة ماكاو الإدارية الخاصة", flag: "🇲🇴" },
  { code: "MP", name: "Northern Mariana Islands", nameAr: "جزر ماريانا الشمالية", flag: "🇲🇵" },
  { code: "MQ", name: "Martinique", nameAr: "جزر المارتينيك", flag: "🇲🇶" },
  { code: "MR", name: "Mauritania", nameAr: "موريتانيا", flag: "🇲🇷" },
  { code: "MS", name: "Montserrat", nameAr: "مونتسرات", flag: "🇲🇸" },
  { code: "MT", name: "Malta", nameAr: "مالطا", flag: "🇲🇹" },
  { code: "MU", name: "Mauritius", nameAr: "موريشيوس", flag: "🇲🇺" },
  { code: "MV", name: "Maldives", nameAr: "جزر المالديف", flag: "🇲🇻" },
  { code: "MW", name: "Malawi", nameAr: "ملاوي", flag: "🇲🇼" },
  { code: "MX", name: "Mexico", nameAr: "المكسيك", flag: "🇲🇽" },
  { code: "MY", name: "Malaysia", nameAr: "ماليزيا", flag: "🇲🇾" },
  { code: "MZ", name: "Mozambique", nameAr: "موزمبيق", flag: "🇲🇿" },
  { code: "NA", name: "Namibia", nameAr: "ناميبيا", flag: "🇳🇦" },
  { code: "NC", name: "New Caledonia", nameAr: "كاليدونيا الجديدة", flag: "🇳🇨" },
  { code: "NE", name: "Niger", nameAr: "النيجر", flag: "🇳🇪" },
  { code: "NF", name: "Norfolk Island", nameAr: "جزيرة نورفولك", flag: "🇳🇫" },
  { code: "NG", name: "Nigeria", nameAr: "نيجيريا", flag: "🇳🇬" },
  { code: "NH", name: "Vanuatu", nameAr: "فانواتو", flag: "🇳🇭" },
  { code: "NI", name: "Nicaragua", nameAr: "نيكاراغوا", flag: "🇳🇮" },
  { code: "NL", name: "Netherlands", nameAr: "هولندا", flag: "🇳🇱" },
  { code: "NO", name: "Norway", nameAr: "النرويج", flag: "🇳🇴" },
  { code: "NP", name: "Nepal", nameAr: "نيبال", flag: "🇳🇵" },
  { code: "NR", name: "Nauru", nameAr: "ناورو", flag: "🇳🇷" },
  { code: "NU", name: "Niue", nameAr: "نيوي", flag: "🇳🇺" },
  { code: "NZ", name: "New Zealand", nameAr: "نيوزيلندا", flag: "🇳🇿" },
  { code: "OM", name: "Oman", nameAr: "عُمان", flag: "🇴🇲" },
  { code: "PA", name: "Panama", nameAr: "بنما", flag: "🇵🇦" },
  { code: "PE", name: "Peru", nameAr: "بيرو", flag: "🇵🇪" },
  { code: "PF", name: "French Polynesia", nameAr: "بولينيزيا الفرنسية", flag: "🇵🇫" },
  { code: "PG", name: "Papua New Guinea", nameAr: "بابوا غينيا الجديدة", flag: "🇵🇬" },
  { code: "PH", name: "Philippines", nameAr: "الفلبين", flag: "🇵🇭" },
  { code: "PK", name: "Pakistan", nameAr: "باكستان", flag: "🇵🇰" },
  { code: "PL", name: "Poland", nameAr: "بولندا", flag: "🇵🇱" },
  { code: "PM", name: "St. Pierre & Miquelon", nameAr: "سان بيير ومكويلون", flag: "🇵🇲" },
  { code: "PN", name: "Pitcairn Islands", nameAr: "جزر بيتكيرن", flag: "🇵🇳" },
  { code: "PR", name: "Puerto Rico", nameAr: "بورتوريكو", flag: "🇵🇷" },
  { code: "PS", name: "Palestinian Territories", nameAr: "الأراضي الفلسطينية", flag: "🇵🇸" },
  { code: "PT", name: "Portugal", nameAr: "البرتغال", flag: "🇵🇹" },
  { code: "PW", name: "Palau", nameAr: "بالاو", flag: "🇵🇼" },
  { code: "PY", name: "Paraguay", nameAr: "باراغواي", flag: "🇵🇾" },
  { code: "QA", name: "Qatar", nameAr: "قطر", flag: "🇶🇦" },
  { code: "QO", name: "Outlying Oceania", nameAr: "أوقيانوسيا النائية", flag: "🇶🇴" },
  { code: "RE", name: "Réunion", nameAr: "روينيون", flag: "🇷🇪" },
  { code: "RH", name: "Zimbabwe", nameAr: "زيمبابوي", flag: "🇷🇭" },
  { code: "RO", name: "Romania", nameAr: "رومانيا", flag: "🇷🇴" },
  { code: "RS", name: "Serbia", nameAr: "صربيا", flag: "🇷🇸" },
  { code: "RU", name: "Russia", nameAr: "روسيا", flag: "🇷🇺" },
  { code: "RW", name: "Rwanda", nameAr: "رواندا", flag: "🇷🇼" },
  { code: "SA", name: "Saudi Arabia", nameAr: "المملكة العربية السعودية", flag: "🇸🇦" },
  { code: "SB", name: "Solomon Islands", nameAr: "جزر سليمان", flag: "🇸🇧" },
  { code: "SC", name: "Seychelles", nameAr: "سيشل", flag: "🇸🇨" },
  { code: "SD", name: "Sudan", nameAr: "السودان", flag: "🇸🇩" },
  { code: "SE", name: "Sweden", nameAr: "السويد", flag: "🇸🇪" },
  { code: "SG", name: "Singapore", nameAr: "سنغافورة", flag: "🇸🇬" },
  { code: "SH", name: "St. Helena", nameAr: "سانت هيلينا", flag: "🇸🇭" },
  { code: "SI", name: "Slovenia", nameAr: "سلوفينيا", flag: "🇸🇮" },
  { code: "SJ", name: "Svalbard & Jan Mayen", nameAr: "سفالبارد وجان ماين", flag: "🇸🇯" },
  { code: "SK", name: "Slovakia", nameAr: "سلوفاكيا", flag: "🇸🇰" },
  { code: "SL", name: "Sierra Leone", nameAr: "سيراليون", flag: "🇸🇱" },
  { code: "SM", name: "San Marino", nameAr: "سان مارينو", flag: "🇸🇲" },
  { code: "SN", name: "Senegal", nameAr: "السنغال", flag: "🇸🇳" },
  { code: "SO", name: "Somalia", nameAr: "الصومال", flag: "🇸🇴" },
  { code: "SR", name: "Suriname", nameAr: "سورينام", flag: "🇸🇷" },
  { code: "SS", name: "South Sudan", nameAr: "جنوب السودان", flag: "🇸🇸" },
  { code: "ST", name: "São Tomé & Príncipe", nameAr: "ساو تومي وبرينسيبي", flag: "🇸🇹" },
  { code: "SU", name: "Russia", nameAr: "روسيا", flag: "🇸🇺" },
  { code: "SV", name: "El Salvador", nameAr: "السلفادور", flag: "🇸🇻" },
  { code: "SX", name: "Sint Maarten", nameAr: "سانت مارتن", flag: "🇸🇽" },
  { code: "SY", name: "Syria", nameAr: "سوريا", flag: "🇸🇾" },
  { code: "SZ", name: "Eswatini", nameAr: "إسواتيني", flag: "🇸🇿" },
  { code: "TA", name: "Tristan da Cunha", nameAr: "تريستان دا كونا", flag: "🇹🇦" },
  { code: "TC", name: "Turks & Caicos Islands", nameAr: "جزر توركس وكايكوس", flag: "🇹🇨" },
  { code: "TD", name: "Chad", nameAr: "تشاد", flag: "🇹🇩" },
  { code: "TF", name: "French Southern Territories", nameAr: "الأقاليم الجنوبية الفرنسية", flag: "🇹🇫" },
  { code: "TG", name: "Togo", nameAr: "توغو", flag: "🇹🇬" },
  { code: "TH", name: "Thailand", nameAr: "تايلاند", flag: "🇹🇭" },
  { code: "TJ", name: "Tajikistan", nameAr: "طاجيكستان", flag: "🇹🇯" },
  { code: "TK", name: "Tokelau", nameAr: "توكيلاو", flag: "🇹🇰" },
  { code: "TL", name: "Timor-Leste", nameAr: "تيمور - ليشتي", flag: "🇹🇱" },
  { code: "TM", name: "Turkmenistan", nameAr: "تركمانستان", flag: "🇹🇲" },
  { code: "TN", name: "Tunisia", nameAr: "تونس", flag: "🇹🇳" },
  { code: "TO", name: "Tonga", nameAr: "تونغا", flag: "🇹🇴" },
  { code: "TP", name: "Timor-Leste", nameAr: "تيمور - ليشتي", flag: "🇹🇵" },
  { code: "TR", name: "Türkiye", nameAr: "تركيا", flag: "🇹🇷" },
  { code: "TT", name: "Trinidad & Tobago", nameAr: "ترينيداد وتوباغو", flag: "🇹🇹" },
  { code: "TV", name: "Tuvalu", nameAr: "توفالو", flag: "🇹🇻" },
  { code: "TW", name: "Taiwan", nameAr: "تايوان", flag: "🇹🇼" },
  { code: "TZ", name: "Tanzania", nameAr: "تنزانيا", flag: "🇹🇿" },
  { code: "UA", name: "Ukraine", nameAr: "أوكرانيا", flag: "🇺🇦" },
  { code: "UG", name: "Uganda", nameAr: "أوغندا", flag: "🇺🇬" },
  { code: "UK", name: "United Kingdom", nameAr: "المملكة المتحدة", flag: "🇺🇰" },
  { code: "UM", name: "U.S. Outlying Islands", nameAr: "جزر الولايات المتحدة النائية", flag: "🇺🇲" },
  { code: "UN", name: "United Nations", nameAr: "الأمم المتحدة", flag: "🇺🇳" },
  { code: "US", name: "United States", nameAr: "الولايات المتحدة", flag: "🇺🇸" },
  { code: "UY", name: "Uruguay", nameAr: "أورغواي", flag: "🇺🇾" },
  { code: "UZ", name: "Uzbekistan", nameAr: "أوزبكستان", flag: "🇺🇿" },
  { code: "VA", name: "Vatican City", nameAr: "الفاتيكان", flag: "🇻🇦" },
  { code: "VC", name: "St. Vincent & Grenadines", nameAr: "سانت فنسنت وجزر غرينادين", flag: "🇻🇨" },
  { code: "VD", name: "Vietnam", nameAr: "فيتنام", flag: "🇻🇩" },
  { code: "VE", name: "Venezuela", nameAr: "فنزويلا", flag: "🇻🇪" },
  { code: "VG", name: "British Virgin Islands", nameAr: "جزر فيرجن البريطانية", flag: "🇻🇬" },
  { code: "VI", name: "U.S. Virgin Islands", nameAr: "جزر فيرجن الأمريكية", flag: "🇻🇮" },
  { code: "VN", name: "Vietnam", nameAr: "فيتنام", flag: "🇻🇳" },
  { code: "VU", name: "Vanuatu", nameAr: "فانواتو", flag: "🇻🇺" },
  { code: "WF", name: "Wallis & Futuna", nameAr: "جزر والس وفوتونا", flag: "🇼🇫" },
  { code: "WS", name: "Samoa", nameAr: "ساموا", flag: "🇼🇸" },
  { code: "XA", name: "Pseudo-Accents", nameAr: "لكنات تجريبية غير أصلية", flag: "🇽🇦" },
  { code: "XB", name: "Pseudo-Bidi", nameAr: "لكنات تجريبية ثنائية الاتجاه", flag: "🇽🇧" },
  { code: "XK", name: "Kosovo", nameAr: "كوسوفو", flag: "🇽🇰" },
  { code: "YD", name: "Yemen", nameAr: "اليمن", flag: "🇾🇩" },
  { code: "YE", name: "Yemen", nameAr: "اليمن", flag: "🇾🇪" },
  { code: "YT", name: "Mayotte", nameAr: "مايوت", flag: "🇾🇹" },
  { code: "YU", name: "Serbia", nameAr: "صربيا", flag: "🇾🇺" },
  { code: "ZA", name: "South Africa", nameAr: "جنوب أفريقيا", flag: "🇿🇦" },
  { code: "ZM", name: "Zambia", nameAr: "زامبيا", flag: "🇿🇲" },
  { code: "ZR", name: "Congo - Kinshasa", nameAr: "الكونغو - كينشاسا", flag: "🇿🇷" },
  { code: "ZW", name: "Zimbabwe", nameAr: "زيمبابوي", flag: "🇿🇼" },
  { code: "ZZ", name: "Unknown Region", nameAr: "منطقة غير معروفة", flag: "🇿🇿" },];

const byCode = new Map(COUNTRIES.map((c) => [c.code.toUpperCase(), c]));
const byName = new Map(COUNTRIES.map((c) => [c.name.toLowerCase(), c]));
const byNameAr = new Map(COUNTRIES.map((c) => [c.nameAr, c]));

export function findCountry(v: string | null | undefined): Country | null {
  if (!v) return null;
  const s = v.trim();
  return byCode.get(s.toUpperCase()) ?? byName.get(s.toLowerCase()) ?? byNameAr.get(s) ?? null;
}

export function countryFlag(v: string | null | undefined): string | null {
  return findCountry(v)?.flag ?? null;
}

export function countryLabel(v: string | null | undefined, lang: string = "en"): string {
  const c = findCountry(v);
  if (!c) return v ?? "";
  return lang === "ar" ? c.nameAr : c.name;
}

export function searchCountries(query: string, limit = 40): Country[] {
  const q = query.trim().toLowerCase();
  if (!q) return COUNTRIES.slice(0, limit);
  const starts: Country[] = [];
  const contains: Country[] = [];
  for (const c of COUNTRIES) {
    const n = c.name.toLowerCase();
    if (n.startsWith(q) || c.code.toLowerCase() === q || c.nameAr.startsWith(query.trim())) starts.push(c);
    else if (n.includes(q) || c.nameAr.includes(query.trim())) contains.push(c);
    if (starts.length >= limit) break;
  }
  return [...starts, ...contains].slice(0, limit);
}
