/**
 * Instant Arabic for every fixed UI phrase in the app.
 * Looked up before the AI translator so the interface never waits on a network call.
 */
export const UI_AR: Record<string, string> = {
  // navigation & tabs
  "Overview": "نظرة عامة",
  "Matches": "المباريات",
  "Match": "مباراة",
  "Teams": "الفرق",
  "Team": "الفريق",
  "Standings": "الترتيب",
  "Squad": "التشكيلة",
  "Info": "معلومات",
  "Statistics": "الإحصائيات",
  "Stats": "الإحصائيات",
  "Media": "الوسائط",
  "Transfers": "الانتقالات",
  "Details": "التفاصيل",
  "News": "الأخبار",
  "Competitions": "المسابقات",
  "Competition": "المسابقة",
  "Players": "اللاعبون",
  "Player": "لاعب",
  "Coaches": "المدربون",
  "Coach": "المدرب",
  "Stadiums": "الملاعب",
  "Stadium": "الملعب",
  "Venue": "الملعب",
  "Awards": "الجوائز",
  "Lineups": "التشكيلات",
  "Timeline": "الأحداث",
  "Chat": "الدردشة",
  "Home": "الرئيسية",
  "Search": "البحث",
  "Settings": "الإعدادات",
  "Favourites": "المفضلة",
  "Favorites": "المفضلة",
  "Countries": "الدول",
  "Country": "الدولة",

  // empty & status states
  "No matches yet": "لا توجد مباريات بعد",
  "No matches on this day.": "لا توجد مباريات في هذا اليوم.",
  "No standings yet": "لا يوجد ترتيب بعد",
  "No teams yet": "لا توجد فرق بعد",
  "No news yet": "لا توجد أخبار بعد",
  "No media yet": "لا توجد وسائط بعد",
  "No transfers yet": "لا توجد انتقالات بعد",
  "No transfers recorded": "لا توجد انتقالات مسجلة",
  "No competition media yet": "لا توجد وسائط للمسابقة بعد",
  "No competition awards yet": "لا توجد جوائز للمسابقة بعد",
  "Not in a table yet": "غير مدرج في جدول بعد",
  "No results": "لا توجد نتائج",
  "No match": "لا توجد نتيجة مطابقة",
  "Type to search": "اكتب للبحث",
  "Competition not found": "لم يتم العثور على المسابقة",
  "Club not found": "لم يتم العثور على النادي",
  "Player not found": "لم يتم العثور على اللاعب",
  "Match not found": "لم يتم العثور على المباراة",
  "Article not found": "لم يتم العثور على المقال",
  "Page not found": "الصفحة غير موجودة",
  "Open media": "عرض الوسائط",
  "Loading": "جارٍ التحميل",
  "Live": "مباشر",
  "Finished": "انتهت",
  "Upcoming": "القادمة",
  "Postponed": "مؤجلة",
  "Cancelled": "ملغاة",
  "Interrupted": "متوقفة",
  "Awarded": "محتسبة",
  "Half time": "الشوط الأول",
  "Full time": "نهاية المباراة",
  "After extra time": "بعد الوقت الإضافي",
  "After penalties": "بعد ركلات الترجيح",
  "TBD": "يُحدد لاحقًا",

  // labels
  "Round": "الجولة",
  "Group": "المجموعة",
  "Season": "الموسم",
  "Seasons": "المواسم",
  "Title holder": "حامل اللقب",
  "Most titles": "الأكثر تتويجًا",
  "Higher division": "الدرجة الأعلى",
  "Lower division": "الدرجة الأدنى",
  "Teams count": "عدد الفرق",
  "Duration": "المدة",
  "Referee": "الحكم",
  "Where to watch": "أين تشاهد",
  "Prediction": "التوقعات",
  "Played": "لعب",
  "Wins": "فوز",
  "Draws": "تعادل",
  "Losses": "خسارة",
  "Goals for": "الأهداف المسجلة",
  "Goals against": "الأهداف المستقبلة",
  "Short name": "الاسم المختصر",
  "Founded": "تأسس",
  "Trophies": "الألقاب",
  "Chairman": "رئيس النادي",
  "City": "المدينة",
  "Capacity": "السعة",
  "Position": "المركز",
  "Shirt": "الرقم",
  "Shirt number": "رقم القميص",
  "Height": "الطول",
  "Date of birth": "تاريخ الميلاد",
  "Nationality": "الجنسية",
  "Market value": "القيمة السوقية",
  "Goalkeeper": "حارس مرمى",
  "Defender": "مدافع",
  "Midfielder": "خط وسط",
  "Forward": "مهاجم",
  "Unknown": "غير محدد",
  "Goalkeepers": "حراس المرمى",
  "Defenders": "المدافعون",
  "Midfielders": "لاعبو الوسط",
  "Forwards": "المهاجمون",
  "No coach": "لا يوجد مدرب",
  "Player of the season": "لاعب الموسم",
  "Player of round": "لاعب الجولة",
  "Recent searches": "عمليات البحث الأخيرة",
  "Clear all": "حذف الكل",
  "Crop image": "قص الصورة",
  "Crop": "قص",
  "Cancel": "إلغاء",
  "Save": "حفظ",
  "Clear": "مسح",
  "Apply": "تطبيق",
  "Back to home": "العودة إلى الرئيسية",
  "Previous day": "اليوم السابق",
  "Next day": "اليوم التالي",
  "Previous matches": "المباريات السابقة",
  "Highlights": "أبرز اللحظات",
  "Read more": "اقرأ المزيد",
  "View": "عرض",
  "Share": "مشاركة",
  "Goal": "هدف",
  "Own goal": "هدف بالخطأ في مرماه",
  "Penalty": "ركلة جزاء",
  "Yellow card": "بطاقة صفراء",
  "Red card": "بطاقة حمراء",
  "Substitution": "تبديل",
  "Assist": "صناعة هدف",
  "Rating": "التقييم",
  "Sport": "الرياضة",
  "No competitions yet": "لا توجد مسابقات بعد",
  "Format": "النظام",
  "Football": "كرة القدم",
  "League": "الدوري",
  "Cup": "الكأس",
  "Knockout": "خروج المغلوب",
  "Groups": "المجموعات",
  "Title winners": "الفرق المتوّجة",
  "Professional": "احترافي",
  "Amateur": "هواة",
  "Youth": "الشباب",
  "International": "دولي",
};
