/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as CoachesIdRouteImport } from './routes/coaches.$id'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions.index'
import { Route as CompetitionsSlugRouteImport } from './routes/competitions.$slug'
import { Route as MatchesIdRouteImport } from './routes/matches.$id'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as PlayersIdRouteImport } from './routes/players.$id'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as VenuesIdRouteImport } from './routes/venues.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesIdRoute = CoachesIdRouteImport.update({
  id: '/coaches/$id',
  path: '/coaches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsSlugRoute = CompetitionsSlugRouteImport.update({
  id: '/competitions/$slug',
  path: '/competitions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/teams/$id',
  path: '/teams/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesIdRoute = VenuesIdRouteImport.update({
  id: '/venues/$id',
  path: '/venues/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contribute': typeof ContributeRoute
  '/download': typeof DownloadRoute
  '/favorites': typeof FavoritesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
  '/coaches/$id': typeof CoachesIdRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/matches/$id': typeof MatchesIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/players/$id': typeof PlayersIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/venues/$id': typeof VenuesIdRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contribute': typeof ContributeRoute
  '/download': typeof DownloadRoute
  '/favorites': typeof FavoritesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
  '/coaches/$id': typeof CoachesIdRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/matches/$id': typeof MatchesIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/players/$id': typeof PlayersIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/venues/$id': typeof VenuesIdRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contribute': typeof ContributeRoute
  '/download': typeof DownloadRoute
  '/favorites': typeof FavoritesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
  '/coaches/$id': typeof CoachesIdRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/matches/$id': typeof MatchesIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/players/$id': typeof PlayersIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/venues/$id': typeof VenuesIdRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contribute'
    | '/download'
    | '/favorites'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/transfers'
    | '/coaches/$id'
    | '/competitions/$slug'
    | '/matches/$id'
    | '/news/$slug'
    | '/players/$id'
    | '/teams/$id'
    | '/venues/$id'
    | '/competitions/'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contribute'
    | '/download'
    | '/favorites'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/transfers'
    | '/coaches/$id'
    | '/competitions/$slug'
    | '/matches/$id'
    | '/news/$slug'
    | '/players/$id'
    | '/teams/$id'
    | '/venues/$id'
    | '/competitions'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contribute'
    | '/download'
    | '/favorites'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/transfers'
    | '/coaches/$id'
    | '/competitions/$slug'
    | '/matches/$id'
    | '/news/$slug'
    | '/players/$id'
    | '/teams/$id'
    | '/venues/$id'
    | '/competitions/'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContributeRoute: typeof ContributeRoute
  DownloadRoute: typeof DownloadRoute
  FavoritesRoute: typeof FavoritesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TransfersRoute: typeof TransfersRoute
  CoachesIdRoute: typeof CoachesIdRoute
  CompetitionsSlugRoute: typeof CompetitionsSlugRoute
  MatchesIdRoute: typeof MatchesIdRoute
  NewsSlugRoute: typeof NewsSlugRoute
  PlayersIdRoute: typeof PlayersIdRoute
  TeamsIdRoute: typeof TeamsIdRoute
  VenuesIdRoute: typeof VenuesIdRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/$id': {
      id: '/coaches/$id'
      path: '/coaches/$id'
      fullPath: '/coaches/$id'
      preLoaderRoute: typeof CoachesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$slug': {
      id: '/competitions/$slug'
      path: '/competitions/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof CompetitionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/teams/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$id': {
      id: '/venues/$id'
      path: '/venues/$id'
      fullPath: '/venues/$id'
      preLoaderRoute: typeof VenuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContributeRoute: ContributeRoute,
  DownloadRoute: DownloadRoute,
  FavoritesRoute: FavoritesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TransfersRoute: TransfersRoute,
  CoachesIdRoute: CoachesIdRoute,
  CompetitionsSlugRoute: CompetitionsSlugRoute,
  MatchesIdRoute: MatchesIdRoute,
  NewsSlugRoute: NewsSlugRoute,
  PlayersIdRoute: PlayersIdRoute,
  TeamsIdRoute: TeamsIdRoute,
  VenuesIdRoute: VenuesIdRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
